// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['app']['App']['AddAccount'](arg1);
}

export function AddNormalBuildJob(arg1) {
  return window['go']['app']['App']['AddNormalBuildJob'](arg1);
}

export function AddResourceBuildJob(arg1) {
  return window['go']['app']['App']['AddResourceBuildJob'](arg1);
}

export function AddTransferRule(arg1) {
  return window['go']['app']['App']['AddTransferRule'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function DeleteAllJobs(arg1) {
  return window['go']['app']['App']['DeleteAllJobs'](arg1);
}

export function DeleteAllTransferRules(arg1) {
  return window['go']['app']['App']['DeleteAllTransferRules'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['app']['App']['DeleteJob'](arg1);
}

export function DeleteTransferRule(arg1) {
  return window['go']['app']['App']['DeleteTransferRule'](arg1);
}

export function ExportJobs(arg1) {
  return window['go']['app']['App']['ExportJobs'](arg1);
}

export function GetAccountDetail(arg1) {
  return window['go']['app']['App']['GetAccountDetail'](arg1);
}

export function GetAccountSettings(arg1) {
  return window['go']['app']['App']['GetAccountSettings'](arg1);
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetAvailableNewBuildings(arg1) {
  return window['go']['app']['App']['GetAvailableNewBuildings'](arg1);
}

export function GetBuildingTypes() {
  return window['go']['app']['App']['GetBuildingTypes']();
}

export function GetBuildings(arg1) {
  return window['go']['app']['App']['GetBuildings'](arg1);
}

export function GetFarmLists(arg1) {
  return window['go']['app']['App']['GetFarmLists'](arg1);
}

export function GetJobs(arg1) {
  return window['go']['app']['App']['GetJobs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetQueueBuildings(arg1) {
  return window['go']['app']['App']['GetQueueBuildings'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['app']['App']['GetStatus'](arg1);
}

export function GetStorage(arg1) {
  return window['go']['app']['App']['GetStorage'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['app']['App']['GetTasks'](arg1);
}

export function GetTransferRules(arg1) {
  return window['go']['app']['App']['GetTransferRules'](arg1);
}

export function GetTroopTypes(arg1, arg2) {
  return window['go']['app']['App']['GetTroopTypes'](arg1, arg2);
}

export function GetVillageSettings(arg1) {
  return window['go']['app']['App']['GetVillageSettings'](arg1);
}

export function GetVillages(arg1) {
  return window['go']['app']['App']['GetVillages'](arg1);
}

export function ImportJobs(arg1, arg2) {
  return window['go']['app']['App']['ImportJobs'](arg1, arg2);
}

export function LogForAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['LogForAccount'](arg1, arg2, arg3);
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['app']['App']['Logout'](arg1);
}

export function MoveJob(arg1, arg2) {
  return window['go']['app']['App']['MoveJob'](arg1, arg2);
}

export function Pause(arg1) {
  return window['go']['app']['App']['Pause'](arg1);
}

export function RefreshVillage(arg1, arg2) {
  return window['go']['app']['App']['RefreshVillage'](arg1, arg2);
}

export function Restart(arg1) {
  return window['go']['app']['App']['Restart'](arg1);
}

export function SaveAccountSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveAccountSettings'](arg1, arg2);
}

export function SaveVillageSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveVillageSettings'](arg1, arg2);
}

export function ToggleFarmList(arg1, arg2) {
  return window['go']['app']['App']['ToggleFarmList'](arg1, arg2);
}

export function UpdateAccount(arg1) {
  return window['go']['app']['App']['UpdateAccount'](arg1);
}
