// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {app} from '../models';

export function AddAccount(arg1:database.AccountDetail):Promise<void>;

export function AddNormalBuildJob(arg1:database.NormalBuildInput):Promise<void>;

export function AddResourceBuildJob(arg1:database.ResourceBuildInput):Promise<void>;

export function AddTransferRule(arg1:database.TransferRuleInput):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteAllJobs(arg1:number):Promise<void>;

export function DeleteAllTransferRules(arg1:number):Promise<void>;

export function DeleteJob(arg1:number):Promise<void>;

export function DeleteTransferRule(arg1:number):Promise<void>;

export function ExportJobs(arg1:number):Promise<string>;

export function GetAccountDetail(arg1:number):Promise<database.AccountDetail>;

export function GetAccountSettings(arg1:number):Promise<Record<string, number>>;

export function GetAccounts():Promise<Array<database.AccountListItem>>;

export function GetAvailableNewBuildings(arg1:number):Promise<Array<app.BuildingTypeInfo>>;

export function GetBuildingTypes():Promise<Array<app.BuildingTypeInfo>>;

export function GetBuildings(arg1:number):Promise<Array<database.BuildingItem>>;

export function GetFarmLists(arg1:number):Promise<Array<database.FarmItem>>;

export function GetJobs(arg1:number):Promise<Array<database.JobItem>>;

export function GetLogs(arg1:number):Promise<Array<app.LogEntry>>;

export function GetQueueBuildings(arg1:number):Promise<Array<database.QueueBuildingItem>>;

export function GetStatus(arg1:number):Promise<number>;

export function GetStorage(arg1:number):Promise<database.StorageDTO>;

export function GetTasks(arg1:number):Promise<Array<app.TaskItem>>;

export function GetTransferRules(arg1:number):Promise<Array<database.TransferRuleDTO>>;

export function GetTroopTypes(arg1:number,arg2:number):Promise<Array<app.TroopTypeInfo>>;

export function GetVillageSettings(arg1:number):Promise<Record<string, number>>;

export function GetVillages(arg1:number):Promise<Array<database.VillageListItem>>;

export function ImportJobs(arg1:number,arg2:string):Promise<void>;

export function LogForAccount(arg1:number,arg2:string,arg3:string):Promise<void>;

export function Login(arg1:number):Promise<void>;

export function Logout(arg1:number):Promise<void>;

export function MoveJob(arg1:number,arg2:string):Promise<void>;

export function Pause(arg1:number):Promise<void>;

export function RefreshVillage(arg1:number,arg2:number):Promise<void>;

export function Restart(arg1:number):Promise<void>;

export function SaveAccountSettings(arg1:number,arg2:Record<string, number>):Promise<void>;

export function SaveVillageSettings(arg1:number,arg2:Record<string, number>):Promise<void>;

export function ToggleFarmList(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAccount(arg1:database.AccountDetail):Promise<void>;
